### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by lehy**

### CODE REVIEW

**Comment by lehy** [comment]
Thank you for the robot and the extension!

**Comment by SuhaylZhao** [comment]
Hi, 
Thank you for your works!

**Comment by SuhaylZhao** [comment]
Hi,

Happy new year and thank you for your works!

We are very glad that you can help us with the translation work. Since translation was not considered initially, not all blocks can be translated. So we updated the code so that all the blocks could be translated.

You can view the newly added content that can be translated here 
https://github.com/Freenove/Makecode-Extension-Rover/commit/d3e9341e7f80cafce5b562e40ebdd7805c783c0a

So can you submit a new translation?

Best wishes.

Thanks!

Suhayl.

**Comment by lehy** [comment]
I have updated the French translation with the added strings. My kids and I wish you a happy new year.

**Pull request merged**
